locator_account:
    resource: "@LocatorAccountBundle/Controller/"
    type:     annotation
    prefix:   /

locator_quittance:
    resource: "@LocatorQuittanceBundle/Controller/"
    type:     annotation
    prefix:   /

locator_main:
    resource: "@LocatorMainBundle/Controller/"
    type:     annotation
    prefix:   /

locator_house:
    resource: "@LocatorHouseBundle/Controller/"
    type:     annotation
    prefix:   /

locator_lease:
    resource: "@LocatorLeaseBundle/Controller/"
    type:     annotation
    prefix:   /

locator_contact:
    resource: "@LocatorContactBundle/Controller/"
    type:     annotation
    prefix:   /


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal